services:
  - type: web
    name: etht-slack-bot
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    region: ohio
    plan: free
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: NODE_ENV
        value: production 